#!/usr/bin/env python3
"""Run every benchmark on every CPU config and print a markdown report.

    python3 scripts/bench.py single pipe bp c256 c1k c4k > docs/results.md

Each benchmark prints one line like
    bench: sort cycles=94628 instret=94093 ctrl=31270 redirect=267 ...
covering only the kernel (not setup or checking). This script collects
those lines and builds the tables.
"""
import subprocess
import sys

BENCHES = ["sort", "matmul", "crc32"]

DESCRIBE = {
    "single": "single-cycle",
    "pipe":   "5-stage pipeline, predict not-taken",
    "bp":     "pipeline + BTB/2-bit predictor",
    "c256":   "pipeline + BP + 256 B I$/D$",
    "c1k":    "pipeline + BP + 1 KB I$/D$",
    "c4k":    "pipeline + BP + 4 KB I$/D$",
}


def run(cfg, bench):
    out = subprocess.run([f"build/sim_{cfg}/Vsoc", f"+hex=build/sw/{bench}.hex"],
                         capture_output=True, text=True)
    last = out.stdout.strip().splitlines()[-1]
    if not last.startswith("PASS"):
        sys.exit(f"{bench} failed on {cfg}: {last}")
    for line in out.stdout.splitlines():
        if line.startswith("bench: "):
            fields = line.split()[2:]
            return {k: int(v) for k, v in (f.split("=") for f in fields)}
    sys.exit(f"{bench} on {cfg}: no bench line")


def pct(num, den):
    return f"{100.0 * num / den:.1f}%" if den else "-"


def main():
    cfgs = sys.argv[1:]
    r = {(c, b): run(c, b) for c in cfgs for b in BENCHES}

    print("# Benchmark results\n")
    print("Generated by `make bench` (scripts/bench.py). Numbers cover only the "
          "benchmark kernel, read from the CPU's own performance counters.\n")
    print("Caches: direct-mapped, 16-byte lines, write-through / no write-allocate, "
          "10-cycle miss penalty. RAM without caches is single-cycle, so the "
          "cached configs are *slower* than `bp`: they model a realistic slow "
          "memory behind the cache.\n")

    print("## Configurations\n")
    print("| Config | Description |")
    print("|---|---|")
    for c in cfgs:
        print(f"| `{c}` | {DESCRIBE.get(c, c)} |")

    print("\n## CPI (cycles per instruction)\n")
    print("| Config | " + " | ".join(BENCHES) + " |")
    print("|---|" + "---|" * len(BENCHES))
    for c in cfgs:
        cells = [f"{r[c, b]['cycles'] / r[c, b]['instret']:.3f}" for b in BENCHES]
        print(f"| `{c}` | " + " | ".join(cells) + " |")

    print("\n## Cycles\n")
    print("| Config | " + " | ".join(BENCHES) + " |")
    print("|---|" + "---|" * len(BENCHES))
    for c in cfgs:
        print(f"| `{c}` | " + " | ".join(f"{r[c, b]['cycles']:,}" for b in BENCHES) + " |")
    print("\nInstructions per kernel: " +
          ", ".join(f"{b} {r[cfgs[0], b]['instret']:,}" for b in BENCHES) + ".")

    pipe_cfgs = [c for c in cfgs if c in ("pipe", "bp")]
    if pipe_cfgs:
        print("\n## Control flow\n")
        print("`redirects` = times the pipeline had to flush and refetch (2 cycles each). "
              "Without a predictor that's every taken branch or jump; with one it's "
              "every misprediction.\n")
        print("| Benchmark | branches+jumps | redirects (`pipe`) | redirects (`bp`) | "
              "BP accuracy |")
        print("|---|---|---|---|---|")
        for b in BENCHES:
            ctrl = r[pipe_cfgs[0], b]["ctrl"]
            rp = r["pipe", b]["redirect"] if "pipe" in cfgs else 0
            rb = r["bp", b]["redirect"] if "bp" in cfgs else 0
            print(f"| {b} | {ctrl:,} | {rp:,} | {rb:,} | {pct(ctrl - rb, ctrl)} |")

    cache_cfgs = [c for c in cfgs if c.startswith("c")]
    if cache_cfgs:
        print("\n## Cache hit rates\n")
        print("| Config | " + " | ".join(f"{b} I$ | {b} D$" for b in BENCHES) + " |")
        print("|---|" + "---|" * (2 * len(BENCHES)))
        for c in cache_cfgs:
            cells = []
            for b in BENCHES:
                x = r[c, b]
                cells.append(pct(x["ic_acc"] - x["ic_miss"], x["ic_acc"]))
                cells.append(pct(x["dc_acc"] - x["dc_miss"], x["dc_acc"]))
            print(f"| `{c}` | " + " | ".join(cells) + " |")
        print("\nHit rate = (accesses - misses) / accesses, where an access is a "
              "completed fetch (I$) or load (D$).")


if __name__ == "__main__":
    main()
